name:                haskell-chess
version:             0.1.0.0
github:              "githubuser/haskell-chess"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-chess#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- MonadRandom
- parsec      # parsing PGN
- text

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - RecordWildCards

executables:
  haskell-chess-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-chess
    default-extensions:
      - OverloadedStrings

tests:
  haskell-chess-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-chess
    - hspec
    - hspec-parsec
    default-extensions:
      - OverloadedStrings
